"""init_schema

Revision ID: 5b6fee4f270e
Revises: 
Create Date: 2026-10-06 03:05:48.190996+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b6fee4f270e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id_contact', sa.UUID(), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_known_customer', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_contact')
    )
    op.create_index(op.f('ix_contacts_email_address'), 'contacts', ['email_address'], unique=True)
    op.create_table('labels',
    sa.Column('id_label', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_label'),
    sa.UniqueConstraint('label_name')
    )
    op.create_table('mailboxes',
    sa.Column('id_mailbox', sa.UUID(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('oauth_access_token', postgresql.BYTEA(), nullable=True),
    sa.Column('oauth_refresh_token', postgresql.BYTEA(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('webhook_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_cursor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_mailbox')
    )
    op.create_index(op.f('ix_mailboxes_email_address'), 'mailboxes', ['email_address'], unique=True)
    op.create_table('emails',
    sa.Column('id_email', sa.UUID(), nullable=False),
    sa.Column('id_mailbox', sa.UUID(), nullable=False),
    sa.Column('id_sender', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.String(length=998), nullable=False),
    sa.Column('thread_id', sa.String(length=998), nullable=True),
    sa.Column('in_reply_to', sa.String(length=998), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_clean', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_agent', sa.String(length=100), nullable=True),
    sa.Column('security_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('html_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_mailbox'], ['mailboxes.id_mailbox'], ),
    sa.ForeignKeyConstraint(['id_sender'], ['contacts.id_contact'], ),
    sa.PrimaryKeyConstraint('id_email'),
    sa.UniqueConstraint('id_mailbox', 'message_id', name='uq_mailbox_message')
    )
    op.create_index(op.f('ix_emails_assigned_agent'), 'emails', ['assigned_agent'], unique=False)
    op.create_index(op.f('ix_emails_id_mailbox'), 'emails', ['id_mailbox'], unique=False)
    op.create_index(op.f('ix_emails_id_sender'), 'emails', ['id_sender'], unique=False)
    op.create_index(op.f('ix_emails_message_id'), 'emails', ['message_id'], unique=False)
    op.create_index(op.f('ix_emails_received_at'), 'emails', ['received_at'], unique=False)
    op.create_index(op.f('ix_emails_status'), 'emails', ['status'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id_attachment', sa.UUID(), nullable=False),
    sa.Column('id_email', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.Column('process_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_email'], ['emails.id_email'], ),
    sa.PrimaryKeyConstraint('id_attachment')
    )
    op.create_index(op.f('ix_attachments_id_email'), 'attachments', ['id_email'], unique=False)
    op.create_index(op.f('ix_attachments_sha256'), 'attachments', ['sha256'], unique=False)
    op.create_table('email_cards',
    sa.Column('id_email', sa.UUID(), nullable=False),
    sa.Column('card_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_email'], ['emails.id_email'], ),
    sa.PrimaryKeyConstraint('id_email')
    )
    op.create_table('email_labels',
    sa.Column('id_email', sa.UUID(), nullable=False),
    sa.Column('id_label', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_email'], ['emails.id_email'], ),
    sa.ForeignKeyConstraint(['id_label'], ['labels.id_label'], ),
    sa.PrimaryKeyConstraint('id_email', 'id_label', 'source')
    )
    op.create_table('email_summaries',
    sa.Column('id_summary', sa.UUID(), nullable=False),
    sa.Column('id_email', sa.UUID(), nullable=False),
    sa.Column('content_summarized', sa.Text(), nullable=True),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_email'], ['emails.id_email'], ),
    sa.PrimaryKeyConstraint('id_summary'),
    sa.UniqueConstraint('id_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_summaries')
    op.drop_table('email_labels')
    op.drop_table('email_cards')
    op.drop_index(op.f('ix_attachments_sha256'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_id_email'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_status'), table_name='emails')
    op.drop_index(op.f('ix_emails_received_at'), table_name='emails')
    op.drop_index(op.f('ix_emails_message_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_id_sender'), table_name='emails')
    op.drop_index(op.f('ix_emails_id_mailbox'), table_name='emails')
    op.drop_index(op.f('ix_emails_assigned_agent'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_mailboxes_email_address'), table_name='mailboxes')
    op.drop_table('mailboxes')
    op.drop_table('labels')
    op.drop_index(op.f('ix_contacts_email_address'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
